<a href="https://colab.research.google.com/github/Saurav-pixel/ML_assignments/blob/main/Assignment7_2002038.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# mounting google drive on colab notebook

from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


# Question 1

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.spatial
from collections import Counter

from sklearn.metrics import accuracy_score

In [ ]:
# Define input features(OR GATE) and (AND GATE) respectively
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
input_features1 = np.array([[0,0],[0,1],[1,0],[1,1]])

print (input_features.shape)
print (input_features)

print (input_features1.shape)
print (input_features1)
# Define target output:
target_output = np.array([[0,1,1,1]])
target_output1 = np.array([[0,0,0,1]])

(4, 2)
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
(4, 2)
[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [ ]:
# Reshaping our target output into vector:
target_output = target_output.reshape(4,1)
print(target_output.shape)
print (target_output)

target_output1 = target_output1.reshape(4,1)
print(target_output1.shape)
print (target_output1)


(4, 1)
[[0]
 [1]
 [1]
 [1]]
(4, 1)
[[0]
 [0]
 [0]
 [1]]


In [ ]:
# Define weights:
weights = np.array([[-0.3],[0.3]])
print(weights.shape)
print (weights)
# Bias weight:
bias = 0.3
# Learning Rate:
lr = 0.85


(2, 1)
[[-0.3]
 [ 0.3]]


In [ ]:
# Activation function:
def sigmoid(x):
  return 1/(1+np.exp(-x))
# Derivative of activation function:
def sigmoid_der(x):
  return sigmoid(x)*(1-sigmoid(x))

In [ ]:
# Running our code 10000 times:
for epoch in range(10000):
  inputs = input_features
  inputs = input_features1
#Feedforward input:
in_o = np.dot(inputs, weights) + bias 
#Feedforward output:
out_o = sigmoid(in_o) 
#Backpropogation
#Calculating error
error = out_o - target_output
error = out_o - target_output1

#Going with the formula:
x = error.sum()
print(x)


1.2945413398491135


In [ ]:
#Calculating derivative:
derror_douto = error
douto_dino = sigmoid_der(out_o)
#Multiplying individual derivatives:
deriv = derror_douto * douto_dino 
#Multiplying with the 3rd individual derivative:
#Finding the transpose of input_features:
inputs = input_features.T
inputs = input_features1.T
deriv_final = np.dot(inputs,deriv)


In [ ]:
#Updating the weights values:
weights -= lr * deriv_final 
#Updating the bias weight value:
for i in deriv:
 bias -= lr * i 
#Check the final values for weight and biasprint (weights)
print(weights)
print (bias) 

[[-0.31651391]
 [ 0.25952179]]
[0.04711738]


In [ ]:
#Predictions 
#Taking inputs:
single_point = np.array([1,0])
 #1st step:
result1 = np.dot(single_point, weights) + bias 
#2nd step:
result2 = sigmoid(result1) 
#Print final result
print(result2) 
#2:
single_point = np.array([1,1]) 
result1 = np.dot(single_point, weights) + bias 
result2 = sigmoid(result1) 
print(result2) 
#3.
single_point = np.array([0,0]) 
result1 = np.dot(single_point, weights) + bias 
result2 = sigmoid(result1) 
print(result2)
#4.
single_point = np.array([0,1]) 
result1 = np.dot(single_point, weights) + bias 
result2 = sigmoid(result1) 
print(result2)

[0.43305525]
[0.49753134]
[0.51177717]
[0.57606471]


# Question 2:  KNN classifier on iris dataset

In [ ]:
import numpy as np
import scipy.spatial
from collections import Counter

from sklearn import datasets
from sklearn.model_selection import train_test_split
iris = datasets.load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state = 42, test_size = 0.2)

In [ ]:
class KNN:
    def __init__(self, k):
        self.k = k
        
    def fit(self, X, y):
        self.X_train = X
        self.y_train = y
        
    def distance(self, X1, X2):
        distance = scipy.spatial.distance.euclidean(X1, X2)
    
    def predict(self, X_test):
        final_output = []
        for i in range(len(X_test)):
            d = []
            votes = []
            for j in range(len(X_train)):
                dist = scipy.spatial.distance.euclidean(X_train[j] , X_test[i])
                d.append([dist, j])
            d.sort()
            d = d[0:self.k]
            for d, j in d:
                votes.append(y_train[j])
            ans = Counter(votes).most_common(1)[0][0]
            final_output.append(ans)
            
        return final_output
    
    def score(self, X_test, y_test):
        predictions = self.predict(X_test)
        return (predictions == y_test).sum() / len(y_test)


In [ ]:
clf = KNN(3)
clf.fit(X_train, y_train)
prediction = clf.predict(X_test)
print(prediction)
for i in prediction:
    print(i, end= ' ')

[1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 0]
1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 

In [ ]:
prediction == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [ ]:
clf.score(X_test, y_test)

1.0