## **Part 1: Python Basic**

1. Write a command to get the Python version you are using.

In [ ]:
!python --version

Python 3.6.9


2. Write a command or program to locate Python site-packages.

In [ ]:
import site
site.getsitepackages()

['/usr/local/lib/python3.6/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3.6/dist-packages']

3. Write a command or program to get the path and name of the
file that is currently executing.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

!find $PWD -name Assignment1_2002038.ipynb

Mounted at /content/drive
/content/drive/MyDrive/Colab Notebooks/Assignment1_2002038.ipynb


4. Write a python program to randomly generate two matrices of
size [2x3 and 3x2] and do the matrix multiplication using
the two generated matrices. (Say A = BC)

In [ ]:
import numpy as np
A = np.random.rand(2,3)
print("First matrix\n",A)

print("\n")

B = np.random.rand(3,2)
print("Second matrix\n",B)

print("\n")

C = np.zeros((2,2))
print("Result matrix \n",C) #initially the result matrix is initialised with zeroes
# matrix multiplication
for i in range(len(A)):
  #iterate through columns of B
  for j in range(len(B[0])):
    #iterate through the rows
    for k in range(len(B)):
      C[i][j] += A[i][k] * B[k][j]


print("\n")
#printing the result of matrix multiplication
print("C = A *B \n")
for r in C:
  print(r)


First matrix
 [[0.67338378 0.88812617 0.28378325]
 [0.41765724 0.8526082  0.61670268]]


Second matrix
 [[0.22207407 0.24213465]
 [0.86231987 0.89067506]
 [0.79960215 0.48771105]]


Result matrix 
 [[0. 0.]
 [0. 0.]]


C = A *B 

[1.14230362 1.09248561]
[1.32108862 1.16129887]


5. Use a for loop to implement the above question five times
and thereafter take the average of all the five matrices
and display the result.

In [ ]:
import numpy as np
A = np.random.rand(2,3)
print("First matrix\n",A)

print("\n")

B = np.random.rand(3,2)
print("Second matrix\n",B)

print("\n")

C = np.zeros((2,2))
print("Result matrix \n",C) #initially the result matrix is initialised with zeroes
for a in range(5):
    # matrix multiplication
  for i in range(len(A)):
    #iterate through columns of B
    for j in range(len(B[0])):
      #iterate through the rows
      for k in range(len(B)):
        C[i][j] += A[i][k] * B[k][j] 



print("\n")
#printing the result of matrix multiplication
print("C = A *B \n")
for r in C:
  print(r)

print("\n")
#printing the average of matrix multiplication
#Average = np.mean(C,axis=0)
#avg2 = np.mean(C,axis=1)
#print(Average)
#print(avg2)
average = C / 5
print(average)

First matrix
 [[0.25638356 0.98708533 0.51450249]
 [0.61443611 0.72262846 0.60245755]]


Second matrix
 [[0.47650797 0.60935125]
 [0.33768147 0.66175841]
 [0.90725726 0.57644022]]


Result matrix 
 [[0. 0.]
 [0. 0.]]


C = A *B 

[4.61137677 5.53009793]
[5.41692963 5.99946816]


[[0.92227535 1.10601959]
 [1.08338593 1.19989363]]


6. Write a program to transfer the matrix (generated in
question 5) to the CSV file and then read the same matrix
and display the transposition of it.

In [ ]:

import numpy as np
import pandas as pd

A = np.random.rand(2,3)
print("First matrix\n",A)

print("\n")

B = np.random.rand(3,2)
print("Second matrix\n",B)

print("\n")

C = np.zeros((2,2))
print("Result matrix \n",C) #initially the result matrix is initialised with zeroes
for a in range(5):
    # matrix multiplication
  for i in range(len(A)):
    #iterate through columns of B
    for j in range(len(B[0])):
      #iterate through the rows
      for k in range(len(B)):
        C[i][j] += A[i][k] * B[k][j] 



print("\n")
#printing the result of matrix multiplication
print("C = A *B \n")
for r in C:
  print(r)

print("\n")
#printing the average of matrix multiplication
#Average = np.mean(C,axis=0)
#avg2 = np.mean(C,axis=1)
#print(Average)
#print(avg2)
average = C / 5

print("average of matrix \n")
print(average)
DF = pd.DataFrame(average)
DF.to_csv("/content/drive/MyDrive/Colab Notebooks/matrix.csv")

#read the values from csv file and save its result in a matrix
import csv

with open('/content/drive/MyDrive/Colab Notebooks/matrix.csv') as csvfile:
    data = list(csv.reader(csvfile))
print("\n")
print("Reading matrix values stored in the CSV file")
print(data)

print("\n")

#converting list into numpy array
arr = np.array(data)
# tranpose of matrix obtained from csv file
transposeMatrix = np.transpose(arr)

print("The transpose of matrix \n")
print(transposeMatrix)

First matrix
 [[0.40965999 0.40285574 0.00617121]
 [0.57325787 0.85661019 0.65169481]]


Second matrix
 [[0.65097438 0.68953689]
 [0.75741658 0.7780354 ]
 [0.35511987 0.23768501]]


Result matrix 
 [[0. 0.]
 [0. 0.]]


C = A *B 

[2.86999649 2.98689255]
[6.26708367 6.08326797]


average of matrix 

[[0.5739993  0.59737851]
 [1.25341673 1.21665359]]


Reading matrix values stored in the CSV file
[['', '0', '1'], ['0', '0.5739992987573295', '0.5973785106944288'], ['1', '1.2534167331524368', '1.216653593527759']]


The transpose of matrix 

[['' '0' '1']
 ['0' '0.5739992987573295' '1.2534167331524368']
 ['1' '0.5973785106944288' '1.216653593527759']]


7. Write a program to find the mean, mode, and median of the above-mentioned matrix.

In [ ]:
import numpy as np
from scipy import stats
A = np.random.rand(2,3)
print("First matrix\n",A)

print("\n")

B = np.random.rand(3,2)
print("Second matrix\n",B)

print("\n")

C = np.zeros((2,2))
#print("Result matrix \n",C) #initially the result matrix is initialised with zeroes
for a in range(5):
    # matrix multiplication
  for i in range(len(A)):
    #iterate through columns of B
    for j in range(len(B[0])):
      #iterate through the rows
      for k in range(len(B)):
        C[i][j] += A[i][k] * B[k][j] 



print("\n")
#printing the result of matrix multiplication
print("C = A *B \n")
for r in C:
  print(r)

print("\n")
#printing the average of matrix multiplication
#Average = np.mean(C,axis=0)
#avg2 = np.mean(C,axis=1)
#print(Average)
#print(avg2)
average = C / 5
print("average of matrix is \n",average)

print("\n")

print("mean of matrix \n",np.mean(average))
print("\n")
print("median of matrix \n", np.median(average))
print("\n")
print("mode of matrix \n",stats.mode(average))

First matrix
 [[0.75884547 0.0118058  0.44761421]
 [0.84334799 0.11538516 0.07780165]]


Second matrix
 [[0.07120831 0.34514396]
 [0.82777157 0.74326448]
 [0.27948339 0.6266509 ]]




C = A *B 

[0.94454673 2.75591805]
[0.88655105 2.12796315]


average of matrix is 
 [[0.18890935 0.55118361]
 [0.17731021 0.42559263]]


mean of matrix 
 0.3357489485124858


median of matrix 
 0.30725098765421544


mode of matrix 
 ModeResult(mode=array([[0.17731021, 0.42559263]]), count=array([[1, 1]]))


8. Write a program to print the upper triangle of the matrix.

In [ ]:

def upper(inputMatrix,rows,cols):
  for i in range(0,rows):
    for j in range(0,cols):
      if(i>j):
        print("0",end =" ");
      else:
        print(inputMatrix[i][j],end=" ")
    
    print(" ")

#main program (Driver code)
import numpy as np
rows = int(input("Enter no. of rows that input matrix should have \n"))
cols = int(input("Enter no. of cols that input matrix should have \n"))

inputMatrix = np.random.rand(rows, cols)
print(inputMatrix)

print("\n")
print("Upper triangular matrix: ")
upper(inputMatrix, rows,cols)


Enter no. of rows that input matrix should have 
3
Enter no. of cols that input matrix should have 
3
[[0.43282133 0.09369541 0.06734352]
 [0.67879012 0.26930191 0.43578563]
 [0.42876387 0.13003444 0.22007919]]


Upper triangular matrix: 
0.4328213320216029 0.09369540643549334 0.06734351634913316  
0 0.26930191072531107 0.4357856283752706  
0 0 0.2200791871905028  


9. Write a Python program to read specific columns of a given CSV file and print the content of the columns. (Column number should be given by the user)

In [ ]:
import csv
with open('/content/sample_data/california_housing_test.csv','r') as csv_file:
 csv_reader = csv.reader(csv_file)
 c = int(input('Enter the column no. of csv file you want to print\n'))
 for line in csv_reader:
   print(line[c])

10. Write a Python program to replace a user-defined number present in the CSV file by the character ‘A’.

In [ ]:
import csv
text = open('/content/sample_data/california_housing_test.csv','r')

#join() function combines all contents of  csv file and formed as a string
text = ''.join([i for i in text])

#search for a number in the text and replace the content
text =text.replace("19","A")

#output.csv is the output file opened in write mode
x = open("/content/drive/MyDrive/Colab Notebooks/output.csv","w")

#all the replaced text  are replaced in output.csv file 
x.writelines(text)
x.close()



## Part 2 : Numpy Basics

1. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [ ]:
import numpy as np
print("array of 10 zeros\n")
print(np.zeros(10))

print("\n")
print("array of 10 ones \n")
print(np.ones(10))

print("\n")
print("array of 10 fives")
print(np.ones(10)*5)

array of 10 zeros

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array of 10 ones 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


2. Write a NumPy program to create an array of all the even integers from 10 to 50

In [ ]:
import numpy as np
array = np.arange(10,51,2)
print("Array of all even integer ranging from 10 to 50\n")
print(array)

Array of all even integer ranging from 10 to 50

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


3. Write a NumPy program to generate a random number between 0 and 1

In [ ]:
import numpy as np
rand_num = np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[1.32418471]


4. Write a NumPy program to save the matrix (generated in question 3) to a text file and load it

In [ ]:
import numpy as np
import os
A = np.arange(12).reshape(4, 3)
print("Original array:")
print(A)
header = 'col1 col2 col3'
np.savetxt('temp.txt', A, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


## Part 3: Pandas Excel

1. Write a python program to read an image and save the image as a matrix to a .csv file using pandas

In [ ]:
from PIL import Image
import numpy as np
import pandas as pd

imframe = Image.open('/content/drive/MyDrive/Colab Notebooks/car.jpg')
npframe = np.array(imframe.getdata())
print(npframe)
imgrgbdf = pd.DataFrame(npframe)
imgrgbdf.to_csv('/content/drive/MyDrive/Colab Notebooks/ImagePixel.csv')

[[223 213 204]
 [223 213 204]
 [223 213 204]
 ...
 [ 82  89 115]
 [ 82  89 115]
 [ 82  89 115]]


2. Write a program to import excel data from the .csv file
(generated in question 1) by excluding the last row and last
column

In [ ]:
import pandas as pd 
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ImagePixel.csv')
print("csv file data before reomving last row and last column")
print(df)
print("\n csv file data after reomving last row and last column\n")
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ImagePixel.csv', skiprows=[50434],usecols=[0,1,2])
print(df)

csv file data before reomving last row and last column
       Unnamed: 0    0    1    2
0               0  223  213  204
1               1  223  213  204
2               2  223  213  204
3               3  223  213  204
4               4  223  213  204
...           ...  ...  ...  ...
50429       50429   81   88  114
50430       50430   81   88  114
50431       50431   82   89  115
50432       50432   82   89  115
50433       50433   82   89  115

[50434 rows x 4 columns]

 csv file data after reomving last row and last column

       Unnamed: 0    0    1
0               0  223  213
1               1  223  213
2               2  223  213
3               3  223  213
4               4  223  213
...           ...  ...  ...
50428       50428   81   88
50429       50429   81   88
50430       50430   81   88
50431       50431   82   89
50432       50432   82   89

[50433 rows x 3 columns]


3. Write a Pandas program to create the today's date

In [ ]:
import pandas as pd
from datetime import date
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(now)

Today's date:
2021-01-13 00:00:00


## Part 4

1. Create a mini calculator to know the age of a person after
putting the range (i.e. date of birth and current date)

In [ ]:
# Python3 code to  calculate age in years 
  
from datetime import date 
  
def calculateAge(birthDate): 
    today = date.today() 
    age = today.year - birthDate.year - 
         ((today.month, today.day) < 
         (birthDate.month, birthDate.day)) 
  
    return age 
      
# Driver code  
print(calculateAge(date(1997, 2, 3)), "years") 